### ISSUE TITLE
The website doesn't take discussions into account

### ISSUE THREAD

**Issue by Jackenmen** [ichard26/next-pr-number#5]
As an example, this shows `164` will be assigned when [164 is already taken](https://github.com/Jackenmen/Issue2527TestRepo/discussions/164) by a discussion:
https://ichard26.github.io/next-pr-number/?owner=Jackenmen&name=Issue2527TestRepo

**Comment by ichard26** [comment]
Yeaa, I don't use this myself so I haven't noticed this bug. I'm surprised people actually use this out in the wild! (I technically have analytics set up, but I haven't looked at them in ages and I don't think they are working anyway.)

I'll get to this soon, but it's a bit of a pain since AFAICT the REST GitHub API doesn't cover repository discussions. I'll have to migrate to the GraphQL API.

Thanks for reporting!

**Comment by Jackenmen** [comment]
I haven't ran into this bug naturally just yet, I was actually curious how you resolved the whole getting next pr number thing and in that process realised that you don't account for discussions and decided to report. But yeah, I do from time to time use this tool, it's really simple, yet helpful so that I don't have to update things *after* creating an issue/PR.
If it's helpful at all, here's how I addressed it for my use:
https://github.com/Cog-Creators/Red-DiscordBot/blob/7dfe24397ee40114f164c919e77a19c1be45cb5b/tools/release_helper.py#L621-L632

**Comment by ichard26** [comment]
Oh hmm, the GraphQL API needs authentication. I could do OAuth, but I don't have time to implement that. Fortunately I'm already renting a VPS so I can just fix this by moving the API query to server side. I'll do that later today.

Thanks GitHub ... 🙃

**Comment by ichard26** [comment]
Annnnd fixed by https://github.com/ichard26/next-pr-number/commit/83f3949cd501a94a672fbf3e2bf09d8cea74a33d :tada: (it looks like a lot of work, but I copied and pasted all of the support code from another FastAPI project.)

@Jackenmen, you don't mind that I copied and pasted your query and data parsing code, do you? I didn't copy the license and I just realized that the project is licensed under GPL-3 which wouldn't be ideal as this repository is MIT licensed.

**Comment by Jackenmen** [comment]
I don't mind - the project as a whole is under GPL but when it comes to my contributions (which the linked file is), I generally tell people I can relicense them under sth like MIT or Apache 2 if they want to use it since using a copyleft license was a choice made before I was involved in the project and I had no influence over it.

Either way, I appreciate you asking, feel free to use it however you wish. Personally, I always appreciate being attributed if someone reuses my code but in this case I don't think that a small chunk that you would be using is copyrightable anyway so I won't insist 😄
